#!/usr/bin/env python3
"""Export Fortran-to-Python routine mapping for traceability docs."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
import re
import sys

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import semantic_overrides


HEADER_RE = re.compile(
    r"^\s*(?:(REAL|INTEGER|LOGICAL|COMPLEX|DOUBLE\s+PRECISION|CHARACTER(?:\*\d+)?)\s+)?"
    r"(PROGRAM|SUBROUTINE|FUNCTION|BLOCK\s+DATA)(?:\s+([A-Za-z_][\w$]*))?",
    flags=re.IGNORECASE,
)


def sanitize_name(name: str) -> str:
    out = re.sub(r"[^0-9a-zA-Z_]", "_", name.strip()).lower()
    if not out:
        out = "unnamed"
    if out[0].isdigit():
        out = f"n_{out}"
    return out


@dataclass(frozen=True)
class Routine:
    name: str
    kind: str
    source_line: int


def parse_fortran_routines(path: Path) -> list[Routine]:
    out: list[Routine] = []
    for lineno, line in enumerate(path.read_text(encoding="utf-8", errors="replace").splitlines(), start=1):
        m = HEADER_RE.match(line)
        if not m:
            continue
        kind = (m.group(2) or "").strip().upper()
        raw_name = (m.group(3) or "").strip()
        if not raw_name:
            continue
        out.append(Routine(name=sanitize_name(raw_name), kind=kind, source_line=lineno))
    return out


def build_markdown(routines: list[Routine]) -> str:
    mapping = semantic_overrides.SEMANTIC_OVERRIDES
    placeholder = getattr(semantic_overrides, "_PLACEHOLDER_OVERRIDES", set())

    lines: list[str] = []
    lines.append("# Fortran Routine Map")
    lines.append("")
    lines.append("Generated by `tools/export_routine_map.py`.")
    lines.append("")
    lines.append(f"- Fortran units: `{len(routines)}`")
    lines.append(f"- Python overrides: `{len(mapping)}`")
    lines.append(f"- Placeholder overrides: `{len(placeholder)}`")
    lines.append("")
    lines.append("| Fortran Routine | Kind | Fortran Line | Python Target | Status |")
    lines.append("| --- | --- | ---: | --- | --- |")

    for r in sorted(routines, key=lambda item: item.name):
        target = mapping.get(r.name)
        if target is None:
            py_target = "_missing_"
            status = "missing"
        else:
            py_target = target.__name__
            status = "placeholder" if r.name in placeholder else "semantic"
        lines.append(
            f"| `{r.name}` | `{r.kind}` | {r.source_line} | `{py_target}` | `{status}` |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Export Fortran routine mapping markdown.")
    parser.add_argument("--fortran", default="fortran_reference/LCModel.f")
    parser.add_argument("--output", default="docs/FORTRAN_ROUTINE_MAP.md")
    args = parser.parse_args()

    routines = parse_fortran_routines(Path(args.fortran))
    text = build_markdown(routines)
    Path(args.output).write_text(text, encoding="utf-8")
    print(f"Wrote {args.output} with {len(routines)} mapped routines.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
